openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          $ref: '#/components/responses/200Success'
        '204':
          $ref: '#/components/responses/204NoContent'
        '400':
          description: Something went wrong
          content:
            application/json:
              schema:
                description: problem stuff
                properties:
                  name:
                    type: string
                    default: bar
  /users/{email}:
    get:
      summary: gets a specific user
      description: Get a user by their email address
      responses:
        '200':
          $ref: '#/components/responses/200Success'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string

components:
  responses:
    200Success:
      description: all fine for now
    204NoContent:
      description: all fine for now

